<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_1cdCMFcoEfG39b7Bn3bMLw" name="DiagramaSolicitudVacaciones" version="1.1.0" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_1cdCMVcoEfG39b7Bn3bMLw" name="SolicitudVacaciones" version="1.1.0">
      <elements xmi:type="process:Lane" xmi:id="_1cdCMlcoEfG39b7Bn3bMLw" name="Empleado (lane) " actor="_1cdCdFcoEfG39b7Bn3bMLw">
        <elements xmi:type="process:StartEvent" xmi:id="_1cdCM1coEfG39b7Bn3bMLw" name="Ingresar Solicitud" outgoing="_1cdCYlcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCNFcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCNVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCNlcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1cdCQFcoEfG39b7Bn3bMLw" name="¿Solicitud aprobada?" outgoing="_1cdCaFcoEfG39b7Bn3bMLw _1cdCa1coEfG39b7Bn3bMLw" incoming="_1cdCZVcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCQVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCQlcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCQ1coEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1cdCRFcoEfG39b7Bn3bMLw" name="Notificar Aprobacion" outgoing="_1cdCcVcoEfG39b7Bn3bMLw" incoming="_1cdCaFcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCRVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCRlcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCR1coEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1cdCSFcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1cdCSVcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1cdCSlcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1cdCS1coEfG39b7Bn3bMLw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1cdCTFcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1cdCTVcoEfG39b7Bn3bMLw" name="Notificar rechazo" outgoing="_1cdCblcoEfG39b7Bn3bMLw" incoming="_1cdCa1coEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCTlcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCT1coEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCUFcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1cdCUVcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1cdCUlcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1cdCU1coEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1cdCVFcoEfG39b7Bn3bMLw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1cdCVVcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_1cdCVlcoEfG39b7Bn3bMLw" name="Fin - Solicitud rechazada" incoming="_1cdCblcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCV1coEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCWFcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCWVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_1cdCWlcoEfG39b7Bn3bMLw" name="Fin - Solicitud aprobada" incoming="_1cdCcVcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCW1coEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCXFcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCXVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mkt1EFcsEfG39b7Bn3bMLw" name="Enviar recordatorio de validacion" outgoing="_t-oo8FcsEfG39b7Bn3bMLw" incoming="_mkvDM1csEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mkucIVcsEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mkucIFcsEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mkucIlcsEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mkucI1csEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mkucJFcsEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mkucJVcsEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mkucJ1csEfG39b7Bn3bMLw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mkucJlcsEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_t-oB4FcsEfG39b7Bn3bMLw" name="Fin  - recordatorio enviado" incoming="_t-oo8FcsEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t-oB4lcsEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t-oB4VcsEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t-oB41csEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_cLzEAFctEfG39b7Bn3bMLw" name="Validar Solicitud" outgoing="_1cdCZVcoEfG39b7Bn3bMLw _mkvDM1csEfG39b7Bn3bMLw" incoming="_1cdCYlcoEfG39b7Bn3bMLw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1cdCOFcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1cdCOVcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1cdCOlcoEfG39b7Bn3bMLw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1cdCO1coEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1cdCPFcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1cdCPVcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1cdCPlcoEfG39b7Bn3bMLw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1cdCP1coEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_1cdCXlcoEfG39b7Bn3bMLw">
        <targetForm xmi:type="expression:Expression" xmi:id="_1cdCX1coEfG39b7Bn3bMLw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_1cdCYFcoEfG39b7Bn3bMLw">
        <targetForm xmi:type="expression:Expression" xmi:id="_1cdCYVcoEfG39b7Bn3bMLw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCYlcoEfG39b7Bn3bMLw" target="_cLzEAFctEfG39b7Bn3bMLw" source="_1cdCM1coEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCY1coEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCZFcoEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCZVcoEfG39b7Bn3bMLw" target="_1cdCQFcoEfG39b7Bn3bMLw" source="_cLzEAFctEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCZlcoEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCZ1coEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCaFcoEfG39b7Bn3bMLw" name="si" target="_1cdCRFcoEfG39b7Bn3bMLw" source="_1cdCQFcoEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCaVcoEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCalcoEfG39b7Bn3bMLw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCa1coEfG39b7Bn3bMLw" name="No" target="_1cdCTVcoEfG39b7Bn3bMLw" source="_1cdCQFcoEfG39b7Bn3bMLw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCbFcoEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCbVcoEfG39b7Bn3bMLw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCblcoEfG39b7Bn3bMLw" target="_1cdCVlcoEfG39b7Bn3bMLw" source="_1cdCTVcoEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCb1coEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCcFcoEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1cdCcVcoEfG39b7Bn3bMLw" target="_1cdCWlcoEfG39b7Bn3bMLw" source="_1cdCRFcoEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1cdCclcoEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1cdCc1coEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mkvDM1csEfG39b7Bn3bMLw" target="_mkt1EFcsEfG39b7Bn3bMLw" source="_cLzEAFctEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mkvDNFcsEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_mkvDNVcsEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t-oo8FcsEfG39b7Bn3bMLw" target="_t-oB4FcsEfG39b7Bn3bMLw" source="_mkt1EFcsEfG39b7Bn3bMLw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t-oo8VcsEfG39b7Bn3bMLw"/>
        <condition xmi:type="expression:Expression" xmi:id="_t-oo8lcsEfG39b7Bn3bMLw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_1cdCdFcoEfG39b7Bn3bMLw" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_1cdCdVcoEfG39b7Bn3bMLw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_1cdCdlcoEfG39b7Bn3bMLw">
        <name xmi:type="expression:Expression" xmi:id="_1cdCd1coEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_1cdCeFcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_1cdCeVcoEfG39b7Bn3bMLw">
        <name xmi:type="expression:Expression" xmi:id="_1cdCelcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_1cdCe1coEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_1cdCfFcoEfG39b7Bn3bMLw">
        <name xmi:type="expression:Expression" xmi:id="_1cdCfVcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_1cdCflcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_1cdCf1coEfG39b7Bn3bMLw">
        <name xmi:type="expression:Expression" xmi:id="_1cdCgFcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_1cdCgVcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_1cdCglcoEfG39b7Bn3bMLw">
        <name xmi:type="expression:Expression" xmi:id="_1cdCg1coEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_1cdChFcoEfG39b7Bn3bMLw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_1cdChVcoEfG39b7Bn3bMLw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_1cdChlcoEfG39b7Bn3bMLw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_1cdCh1coEfG39b7Bn3bMLw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_1cdCiFcoEfG39b7Bn3bMLw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_1cdCiVcoEfG39b7Bn3bMLw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_1cdCilcoEfG39b7Bn3bMLw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_1cdCi1coEfG39b7Bn3bMLw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_1cdCjFcoEfG39b7Bn3bMLw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_1cdCjVcoEfG39b7Bn3bMLw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_1cdCjlcoEfG39b7Bn3bMLw" type="Process" element="_1cdCMFcoEfG39b7Bn3bMLw" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_1cdCj1coEfG39b7Bn3bMLw" type="2007" element="_1cdCMVcoEfG39b7Bn3bMLw">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCkFcoEfG39b7Bn3bMLw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCkVcoEfG39b7Bn3bMLw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_1cdCklcoEfG39b7Bn3bMLw" type="3007" element="_1cdCMlcoEfG39b7Bn3bMLw">
          <children xmi:type="notation:DecorationNode" xmi:id="_1cdCk1coEfG39b7Bn3bMLw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_1cdClFcoEfG39b7Bn3bMLw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_1cdClVcoEfG39b7Bn3bMLw" type="3002" element="_1cdCM1coEfG39b7Bn3bMLw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCllcoEfG39b7Bn3bMLw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCl1coEfG39b7Bn3bMLw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCmFcoEfG39b7Bn3bMLw" x="62" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1cdCnFcoEfG39b7Bn3bMLw" type="3008" element="_1cdCQFcoEfG39b7Bn3bMLw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCnVcoEfG39b7Bn3bMLw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCnlcoEfG39b7Bn3bMLw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCn1coEfG39b7Bn3bMLw" x="350" y="138" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1cdCoFcoEfG39b7Bn3bMLw" type="3027" element="_1cdCRFcoEfG39b7Bn3bMLw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCoVcoEfG39b7Bn3bMLw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdColcoEfG39b7Bn3bMLw" x="590" y="10" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1cdCo1coEfG39b7Bn3bMLw" type="3027" element="_1cdCTVcoEfG39b7Bn3bMLw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCpFcoEfG39b7Bn3bMLw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCpVcoEfG39b7Bn3bMLw" x="603" y="217" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1cdCplcoEfG39b7Bn3bMLw" type="3003" element="_1cdCVlcoEfG39b7Bn3bMLw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCp1coEfG39b7Bn3bMLw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCqFcoEfG39b7Bn3bMLw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCqVcoEfG39b7Bn3bMLw" x="806" y="234"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1cdCqlcoEfG39b7Bn3bMLw" type="3003" element="_1cdCWlcoEfG39b7Bn3bMLw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1cdCq1coEfG39b7Bn3bMLw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCrFcoEfG39b7Bn3bMLw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCrVcoEfG39b7Bn3bMLw" x="835" y="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mkvDMFcsEfG39b7Bn3bMLw" type="3027" element="_mkt1EFcsEfG39b7Bn3bMLw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mkvDMlcsEfG39b7Bn3bMLw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mkvDMVcsEfG39b7Bn3bMLw" x="162" y="306" width="119" height="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_t-oB5FcsEfG39b7Bn3bMLw" type="3003" element="_t-oB4FcsEfG39b7Bn3bMLw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_t-oB5lcsEfG39b7Bn3bMLw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_t-oB51csEfG39b7Bn3bMLw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t-oB5VcsEfG39b7Bn3bMLw" x="368" y="306"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cMF-8FctEfG39b7Bn3bMLw" type="3027" element="_cLzEAFctEfG39b7Bn3bMLw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_cMKQYFctEfG39b7Bn3bMLw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cMF-8VctEfG39b7Bn3bMLw" x="158" y="156" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_1cdCrlcoEfG39b7Bn3bMLw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_1cdCr1coEfG39b7Bn3bMLw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_1cdCsFcoEfG39b7Bn3bMLw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_1cdCsVcoEfG39b7Bn3bMLw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCslcoEfG39b7Bn3bMLw" x="53" y="10" width="975" height="426"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_1cdCs1coEfG39b7Bn3bMLw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdCtFcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_1cdCtVcoEfG39b7Bn3bMLw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_1cdCtlcoEfG39b7Bn3bMLw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1cdCt1coEfG39b7Bn3bMLw" width="1003" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_1cdCuFcoEfG39b7Bn3bMLw"/>
    <edges xmi:type="notation:Connector" xmi:id="_1cdCuVcoEfG39b7Bn3bMLw" type="4001" element="_1cdCYlcoEfG39b7Bn3bMLw" source="_1cdClVcoEfG39b7Bn3bMLw" target="_cMF-8FctEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCulcoEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCu1coEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdCvFcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdCvVcoEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1cdCvlcoEfG39b7Bn3bMLw" type="4001" element="_1cdCZVcoEfG39b7Bn3bMLw" source="_cMF-8FctEfG39b7Bn3bMLw" target="_1cdCnFcoEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCv1coEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCwFcoEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdCwVcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdCwlcoEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1cdCw1coEfG39b7Bn3bMLw" type="4001" element="_1cdCaFcoEfG39b7Bn3bMLw" source="_1cdCnFcoEfG39b7Bn3bMLw" target="_1cdCoFcoEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCxFcoEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCxVcoEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdCxlcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdCx1coEfG39b7Bn3bMLw" points="[0, -21, -295, 90]$[0, -83, -295, 28]$[219, -83, -76, 28]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1cdCyFcoEfG39b7Bn3bMLw" type="4001" element="_1cdCa1coEfG39b7Bn3bMLw" source="_1cdCnFcoEfG39b7Bn3bMLw" target="_1cdCo1coEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCyVcoEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCylcoEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdCy1coEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdCzFcoEfG39b7Bn3bMLw" points="[3, 19, -261, -87]$[3, 118, -261, 12]$[201, 118, -63, 12]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1cdCzVcoEfG39b7Bn3bMLw" type="4001" element="_1cdCblcoEfG39b7Bn3bMLw" source="_1cdCo1coEfG39b7Bn3bMLw" target="_1cdCplcoEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdCzlcoEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdCz1coEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdC0FcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdC0VcoEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1cdC0lcoEfG39b7Bn3bMLw" type="4001" element="_1cdCcVcoEfG39b7Bn3bMLw" source="_1cdCoFcoEfG39b7Bn3bMLw" target="_1cdCqlcoEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1cdC01coEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1cdC1FcoEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1cdC1VcoEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1cdC1lcoEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mkvDNlcsEfG39b7Bn3bMLw" type="4001" element="_mkvDM1csEfG39b7Bn3bMLw" source="_cMF-8FctEfG39b7Bn3bMLw" target="_mkvDMFcsEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mkvDOVcsEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mkvDOlcsEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mkvDN1csEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mkvDOFcsEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t-oo81csEfG39b7Bn3bMLw" type="4001" element="_t-oo8FcsEfG39b7Bn3bMLw" source="_mkvDMFcsEfG39b7Bn3bMLw" target="_t-oB5FcsEfG39b7Bn3bMLw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t-oo9lcsEfG39b7Bn3bMLw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t-oo91csEfG39b7Bn3bMLw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t-oo9FcsEfG39b7Bn3bMLw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t-oo9VcsEfG39b7Bn3bMLw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
