<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_w-mH8FZFEfG5T9dEgslXqA" name="DiagramaSolicitudVacaciones" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_w-mH8VZFEfG5T9dEgslXqA" name="SolicitudVacaciones" version="1.0.0">
      <elements xmi:type="process:Lane" xmi:id="_w-mH8lZFEfG5T9dEgslXqA" name="Empleado (lane) " actor="_w-mIC1ZFEfG5T9dEgslXqA">
        <elements xmi:type="process:StartEvent" xmi:id="_w-mH81ZFEfG5T9dEgslXqA" name="Ingresar Solicitud" outgoing="_w-mICFZFEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w-mH9FZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w-mH9VZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w-mH9lZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wSyDcFZIEfG5T9dEgslXqA" name="Validar Solicitud" outgoing="_nOXcoFZIEfG5T9dEgslXqA" incoming="_w-mICFZFEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w-mH-FZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w-mH-VZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w-mH-lZFEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_w-mH-1ZFEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_w-mH_FZFEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_w-mH_VZFEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_w-mH_lZFEfG5T9dEgslXqA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_w-mH_1ZFEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="__URFoFZIEfG5T9dEgslXqA" name="¿Solicitud aprobada?" outgoing="_L3vNQFZJEfG5T9dEgslXqA _OnKygFZKEfG5T9dEgslXqA" incoming="_nOXcoFZIEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nNmAkFZIEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nNkycFZIEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nNmAkVZIEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_L3jAAFZJEfG5T9dEgslXqA" name="Notificar Aprobacion" outgoing="_bP7NUFZLEfG5T9dEgslXqA" incoming="_L3vNQFZJEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L3n4gFZJEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L3mqYFZJEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L3n4gVZJEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L3n4glZJEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L3n4g1ZJEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L3n4hFZJEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L3n4hlZJEfG5T9dEgslXqA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L3n4hVZJEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OnCPoFZKEfG5T9dEgslXqA" name="Notificar rechazo" outgoing="_fYdlcFZKEfG5T9dEgslXqA" incoming="_OnKygFZKEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OnFS8VZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OnFS8FZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OnFS8lZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OnF6AFZKEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OnF6AVZKEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OnF6AlZKEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OnF6BFZKEfG5T9dEgslXqA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OnF6A1ZKEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fYVpoFZKEfG5T9dEgslXqA" name="Fin - Solicitud rechazada" incoming="_fYdlcFZKEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fYYs8VZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fYYs8FZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fYYs8lZKEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_bPuZAFZLEfG5T9dEgslXqA" name="Fin - Solicitud aprobada" incoming="_bP7NUFZLEfG5T9dEgslXqA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bPz4kVZLEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bPz4kFZLEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bPz4klZLEfG5T9dEgslXqA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_w-mIBFZFEfG5T9dEgslXqA">
        <targetForm xmi:type="expression:Expression" xmi:id="_w-mIBVZFEfG5T9dEgslXqA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_w-mIBlZFEfG5T9dEgslXqA">
        <targetForm xmi:type="expression:Expression" xmi:id="_w-mIB1ZFEfG5T9dEgslXqA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w-mICFZFEfG5T9dEgslXqA" target="_wSyDcFZIEfG5T9dEgslXqA" source="_w-mH81ZFEfG5T9dEgslXqA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w-mICVZFEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_w-mIClZFEfG5T9dEgslXqA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nOXcoFZIEfG5T9dEgslXqA" target="__URFoFZIEfG5T9dEgslXqA" source="_wSyDcFZIEfG5T9dEgslXqA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nOZ44FZIEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_nOZ44VZIEfG5T9dEgslXqA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L3vNQFZJEfG5T9dEgslXqA" name="si" target="_L3jAAFZJEfG5T9dEgslXqA" source="__URFoFZIEfG5T9dEgslXqA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L3xCcFZJEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_L3xCcVZJEfG5T9dEgslXqA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OnKygFZKEfG5T9dEgslXqA" name="No" target="_OnCPoFZKEfG5T9dEgslXqA" source="__URFoFZIEfG5T9dEgslXqA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OnLZkFZKEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_OnLZkVZKEfG5T9dEgslXqA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fYdlcFZKEfG5T9dEgslXqA" target="_fYVpoFZKEfG5T9dEgslXqA" source="_OnCPoFZKEfG5T9dEgslXqA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fYdlcVZKEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_fYdlclZKEfG5T9dEgslXqA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bP7NUFZLEfG5T9dEgslXqA" target="_bPuZAFZLEfG5T9dEgslXqA" source="_L3jAAFZJEfG5T9dEgslXqA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bP70YFZLEfG5T9dEgslXqA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bP70YVZLEfG5T9dEgslXqA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_w-mIC1ZFEfG5T9dEgslXqA" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_w-mIDFZFEfG5T9dEgslXqA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-mIDVZFEfG5T9dEgslXqA">
        <name xmi:type="expression:Expression" xmi:id="_w-mIDlZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-mID1ZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-mIEFZFEfG5T9dEgslXqA">
        <name xmi:type="expression:Expression" xmi:id="_w-mIEVZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-mIElZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-mIE1ZFEfG5T9dEgslXqA">
        <name xmi:type="expression:Expression" xmi:id="_w-mIFFZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-mIFVZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-mIFlZFEfG5T9dEgslXqA">
        <name xmi:type="expression:Expression" xmi:id="_w-mIF1ZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-mIGFZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-mIGVZFEfG5T9dEgslXqA">
        <name xmi:type="expression:Expression" xmi:id="_w-mIGlZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-mIG1ZFEfG5T9dEgslXqA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_w-mIHFZFEfG5T9dEgslXqA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_w-mIHVZFEfG5T9dEgslXqA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_w-mIHlZFEfG5T9dEgslXqA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_w-mIH1ZFEfG5T9dEgslXqA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_w-mIIFZFEfG5T9dEgslXqA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_w-mIIVZFEfG5T9dEgslXqA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_w-mIIlZFEfG5T9dEgslXqA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_w-mII1ZFEfG5T9dEgslXqA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_w-mIJFZFEfG5T9dEgslXqA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_w-mvAFZFEfG5T9dEgslXqA" type="Process" element="_w-mH8FZFEfG5T9dEgslXqA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_w-mvAVZFEfG5T9dEgslXqA" type="2007" element="_w-mH8VZFEfG5T9dEgslXqA">
      <children xmi:type="notation:DecorationNode" xmi:id="_w-mvAlZFEfG5T9dEgslXqA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_w-mvA1ZFEfG5T9dEgslXqA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_w-mvBFZFEfG5T9dEgslXqA" type="3007" element="_w-mH8lZFEfG5T9dEgslXqA">
          <children xmi:type="notation:DecorationNode" xmi:id="_w-mvBVZFEfG5T9dEgslXqA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_w-mvBlZFEfG5T9dEgslXqA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_w-mvClZFEfG5T9dEgslXqA" type="3002" element="_w-mH81ZFEfG5T9dEgslXqA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w-mvC1ZFEfG5T9dEgslXqA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w-mvDFZFEfG5T9dEgslXqA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w-mvDVZFEfG5T9dEgslXqA" x="62" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wS2U4FZIEfG5T9dEgslXqA" type="3027" element="_wSyDcFZIEfG5T9dEgslXqA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wS278FZIEfG5T9dEgslXqA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wS2U4VZIEfG5T9dEgslXqA" x="158" y="157" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__URss1ZIEfG5T9dEgslXqA" type="3008" element="__URFoFZIEfG5T9dEgslXqA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__URstVZIEfG5T9dEgslXqA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__URstlZIEfG5T9dEgslXqA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__URstFZIEfG5T9dEgslXqA" x="350" y="138" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L3q70FZJEfG5T9dEgslXqA" type="3027" element="_L3jAAFZJEfG5T9dEgslXqA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L3sxAFZJEfG5T9dEgslXqA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L3q70VZJEfG5T9dEgslXqA" x="590" y="10" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OnHvMFZKEfG5T9dEgslXqA" type="3027" element="_OnCPoFZKEfG5T9dEgslXqA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OnI9UFZKEfG5T9dEgslXqA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OnHvMVZKEfG5T9dEgslXqA" x="603" y="217" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fYZ7EFZKEfG5T9dEgslXqA" type="3003" element="_fYVpoFZKEfG5T9dEgslXqA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fYZ7ElZKEfG5T9dEgslXqA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fYZ7E1ZKEfG5T9dEgslXqA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fYZ7EVZKEfG5T9dEgslXqA" x="806" y="234"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bP2U0FZLEfG5T9dEgslXqA" type="3003" element="_bPuZAFZLEfG5T9dEgslXqA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bP4xEFZLEfG5T9dEgslXqA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bP5YIFZLEfG5T9dEgslXqA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bP274FZLEfG5T9dEgslXqA" x="835" y="42"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_w-mvDlZFEfG5T9dEgslXqA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_w-mvD1ZFEfG5T9dEgslXqA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_w-mvEFZFEfG5T9dEgslXqA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_w-mvEVZFEfG5T9dEgslXqA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w-mvElZFEfG5T9dEgslXqA" x="53" y="10" width="904" height="343"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_w-mvE1ZFEfG5T9dEgslXqA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_w-mvFFZFEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_w-mvFVZFEfG5T9dEgslXqA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_w-mvFlZFEfG5T9dEgslXqA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w-mvF1ZFEfG5T9dEgslXqA" width="1003" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_w-mvGFZFEfG5T9dEgslXqA"/>
    <edges xmi:type="notation:Connector" xmi:id="_w-mvGVZFEfG5T9dEgslXqA" type="4001" element="_w-mICFZFEfG5T9dEgslXqA" source="_w-mvClZFEfG5T9dEgslXqA" target="_wS2U4FZIEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w-mvGlZFEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w-mvG1ZFEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w-mvHFZFEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w-mvHVZFEfG5T9dEgslXqA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nPmywFZIEfG5T9dEgslXqA" type="4001" element="_nOXcoFZIEfG5T9dEgslXqA" source="_wS2U4FZIEfG5T9dEgslXqA" target="__URss1ZIEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nPon8FZIEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nPon8VZIEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nPmywVZIEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nPmywlZIEfG5T9dEgslXqA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L3xpgFZJEfG5T9dEgslXqA" type="4001" element="_L3vNQFZJEfG5T9dEgslXqA" source="__URss1ZIEfG5T9dEgslXqA" target="_L3q70FZJEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L3yQkFZJEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L3yQkVZJEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L3xpgVZJEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L3xpglZJEfG5T9dEgslXqA" points="[0, -21, -295, 90]$[0, -83, -295, 28]$[219, -83, -76, 28]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OnMAoFZKEfG5T9dEgslXqA" type="4001" element="_OnKygFZKEfG5T9dEgslXqA" source="__URss1ZIEfG5T9dEgslXqA" target="_OnHvMFZKEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OnMnsFZKEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OnMnsVZKEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OnMAoVZKEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OnMAolZKEfG5T9dEgslXqA" points="[3, 19, -261, -87]$[3, 118, -261, 12]$[201, 118, -63, 12]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fYdlc1ZKEfG5T9dEgslXqA" type="4001" element="_fYdlcFZKEfG5T9dEgslXqA" source="_OnHvMFZKEfG5T9dEgslXqA" target="_fYZ7EFZKEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fYdldlZKEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fYdld1ZKEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fYdldFZKEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fYdldVZKEfG5T9dEgslXqA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bP8bcFZLEfG5T9dEgslXqA" type="4001" element="_bP7NUFZLEfG5T9dEgslXqA" source="_L3q70FZJEfG5T9dEgslXqA" target="_bP2U0FZLEfG5T9dEgslXqA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bP8bc1ZLEfG5T9dEgslXqA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bP9pkFZLEfG5T9dEgslXqA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bP8bcVZLEfG5T9dEgslXqA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bP8bclZLEfG5T9dEgslXqA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
